sName = str(input())
a = eval(input())
v = eval(input())
length = v * v / (2 a)
print("The acceleration of",sName,"is",a%.2f,"M/s,the take-off speed is",v%.2f,"M/s,and the shortest take-off run way length is",length%.2f,"M.")
