airname = input()
aira = input()
airv = input()
length = airv*airv/(2*aira)
print('The acceleration of B350 is %f M / s, the take-off speed is %f M / s, and the shortest take-off runway length is %.2f M.'%(aira,airv,length)
