sname=input()
jiasudu=float(input())
sudu=float(input())
lenh=sudu*sudu/(2*jiasudu)
print("The acceleration of %s is %.2f M / S, the take-off speed is %2f M / S, and the shortest take-off runway lenh is %2f M"%)
