#存储学生Zhang成绩的字典结构如下：
#stu={"name":"Zhang","english":80,"python":90,"math":100}
#1）请使用上述结构输入学生的name及english、python和math三门课的成绩并存储到字典stu中(不考虑空数据的情况)；
#2）计算该同学的平均成绩，同时在字典中添加关键字"avg"用来表示平均成绩；
#3）由高到低排序该学生的各科成绩；
#4）输出该学生的姓名，各科成绩（保留两位小数）和平均成绩（保留两位小数）。
lst=input()
lst11=lst.split(" ")
name=lst11[0]
englishgrade=int(lst11[1])
pythongrade=int(lst11[2])
mathgrade=int(lst11[3])
stu={'name':name,'english':englishgrade,'python':pythongrade,'math':mathgrade}
avg=(englishgrade+pythongrade+mathgrade)/3
stu['avg']=round(avg,2)
lst2=[stu['english'],stu['python'],stu['math']]
lst2.sort(reverse=True)
lst1=[stu['name'],*lst2,stu['avg']]
print(*lst1)
