stu={}
(sname,senglish,spython,smath)=input().split(' ')
stu['name']=sname
stu['english']=senglish
stu['python']=spython
stu['math']=smath
savg=(int(senglish)+int(spython)+int(smath))/3
stu['avg']=savg
grade=[senglish,spython,smath]
grade.sort(reverse=True)
a=eval(grade[0])
b=eval(grade[1])
c=eval(grade[2])
print(stu['name'],'%.2f'%a,'%.2f'%b,'%.2f'%c,'%.2f'%savg,sep='')
