stu={}
(sname,senglish,spython,smath)=eval(input().split(' '))
stu['name']=sname
stu['english']=senglish
stu['python']=spython
stu['math']=smath
savg=(senglish+spython+smath)/3
stu['avg']=savg
grade=(senglish,spython,smath)
grade.sort(reverse=True)
a=grade[0]
b=grade[1]
c=grade[2]
print(stu['name'],'%.2f'%a,'%.2f'%b,'%.2f'%c,'%.2f'%savg,sep='')
