ls=input().split()
dic={}
ls2=[]
dic['name']=ls[0]
dic["english"]=int(ls[1])
dic["python"]=int(ls[2])
dic["math"]=int(ls[3])
dic['avg']=(int(ls[1])+int(ls[2])+int(ls[3]))/3
ls2.append(dic.get('english'))
ls2.append(dic.get("python"))
ls2.append(dic.get("math"))
ls2.sort(reverse=True)
a=ls[0]
b,c,d=ls2
print(a,'%.2f'%b,'%.2f'%c,'%.2f'%d,dic.get('avg'))
