stu={}
a=input()
a=a.split()
l=[int(a[1],a[2],a[3])]
l=sorted(l,reverse=True)
stu['name']=a[0]
stu['english']=int(a[1])
stu['python']=int(a[2])
stu['math']=int(a[3])
stu['avg']=(stu['english']+stu['python']+stu['math'])/3
print(stu['name'],"%.2f","%.2f","%.2f","%.2f"%(l[0][1],l[1][1],l[2][1],stu['avg']))
