a=input().split()
b={}
b['name']=a[0]
b['english']=int(a[1])
b['python']=int(a[2])
b['math']=int(a[3])
avg=(b['english']+b['python']+b['math'])/3
b['avg']=avg
c=[int(a[1]),int(a[2]),int(a[3])]
c.sort(reverse=True)
print(a[0],'%.2f,%.2f,%.2f,%.2f'%(c[0],c[1],c[2],avg))
