import turtle,random
t=turtle.Pen()
t.penup()
t.bk(600)
t.pendown()
colorlist=('yellow','red','blue','black','pink','purple','green')
t.pensize(50)
t.seth(-50)
for i in range(6):
    t.color(random.choice(colorlist))
    t.circle(50,100)
    t.circle(-50,100)
t.color("green")
t.circle(50,50)
t.color('black')
t.fd(80)
t.circle(50,180)
t.color('blue')
t.fd(60)
turtle.done()
