a,b,c=(input()).split(",")
score=eval(input())
list=[]
list[1]=[a]
list[2]=[b]
list[3]=[c]
list1.append(score[0])
list2.append(score[1])
list3.append(score[2])
list.append(list1)
list.append(list2)
list.append(list3)
print(list)
