a=input().split(",")
b=input().split(",")
b1= str(b).replace("'", "")
list_Data = b1.replace("[", "").replace("]", "").split(", ")
list_Data = [int(x) for x in list_Data]
c=map(lambda t: [*t], zip(a, d))
c=sorted(c, key=lambda t: t[1])
print(c)
print(a)
print(b)
