name=input()
a=eval(input())
v=eval(input())
l=v**2/(2*a)
text='The acceleration of %s is %.2f M/s, the take-off spped is %.2f M/s, and the shortest take-off runway length is %.2f M.'%(name,a,v,l)
print(text)
