name=eval(input())
a=eval(input())
v=eval(input())
length=v*v/(2*a)
print('The acceleration of %s is %2f M / s , the take-off speed is %2f M / s, and the shortest take-off runway %2f is 503.92 M.'%(name,a,v,length))
