plane=input()
a=input()
v=input()
l=v**2/(2*a)
a="%.f2"%(a)
v="%.f2"%(v)
l="%.f2"%(l)
print("The acceleration of ",plane," is ",a," M/s,the take-off speed is ",v," M / s, and the shortest take-off runway length is ",l," M.")
