boys=input("")
girls=input("")
bi2=int(boys)/(int(boys)+int(girls))
gi2=int(girls)/(int(boys)+int(girls))
print("The male students ratio is",'{:.2f}%,'.format(bi2*100),"the female students ratio is",'{:.2f}%'.format(gi2*100))
