name=input ()
a=eval(input())
v=eval(input())
length=v*v/(2*a)
print("The acceleration of %s is %.2fM /s , the take-off speed is %.2fM /s  , and the shortest take-off runway length is %.2f M."%(name,a,v,length))
