sName = input()
a = float(input())
v = float(input())
L = v * v/(2 * a)
sText = "The acceleration of %s is %.2f M/s, the take-off speed is %.2f M/s, and the shortest take-off runway length is %.2f M" % (sName,v,L)
print(sText)
