n=input()
a=float(input())
v=float(input())
l=v*v/(2*a)
stxet="The acceleration of %s is %.2f M / s, the take-off speed is %.2f M / s, and the shortest take-off runway length is %.2f M."%(n,a,v,l)
print(stxet)
