aa=input()
aaa=eval(input())
vvv=eval(input())
yy = vvv*vvv/(2*(aaa))
print ("The acceleration of %s is %.2f M / s, the take-off speed is %.2f M / s, and the shortest take-off runway length is %.2f M."%(aa,aaa,vvv,yy))
