name=input()
a=eval(input())
v=eval(input())
length=v*v/(2*a)
print('The acceleration of {} is {:.2f},the take-off speed is {:.2f}, and the shortest take-off runway length is {:.2f}'.format(name,a,v,length)) 
