iplane=input()
a=eval(input())
v=eval(input())
length=v*v/(2*a)
sText="The acceleration of %s is %.2f, the take-off speed is %.2f M/s,and the shortest take-off runaway length is %.2f M."%(iplane,a,v,length)
print(sText)
