sName=eval(input())
ia=eval(input())
iv=eval(input())
iLength=eval(iv*iv/2(ia))
print("The acceleration of sName is ia%2f,the take-off speed is iv%2f,and the shortest take-off runway length is iLength%2f")
