a = input()
b = eval(input())
c = eval(input())
l = c*c/(2*b)
print("The acceleration of",a ,"is","%.2f"%b,"M / s,","the take-off speed is","%.2f"%c, "M / s,", "and the shortest take-off runaway lenth is","%.2f"%l, "M.")
