Sname=input()
a1=input()
v1=input()
a2=float(a1)
v2=float(v1)
x1=v2**2/2/a2
a=round(a2,2)
v=round(v2,2)
x=round(x1,2)
print("The acceleration of",Sname,"is",a,"M / s","the take-off speed is " ,v,"M / s",", and the shortest take-off runway length is",x,"M")
