sAcceleration=input()
sVelocity=input()
sAcceleration=float(sAcceleration)
sVelocity=float(sVelocity)
Length=sVelocity*sVelocity/(2*sAcceleration)
sName=input("")
stext="The acceleration of %s is %.2f M/s,the take-off speed is %.2f M/s,and the shortest take-off runway length is %.2f M."%(sName,sAcceleration,sVelocity,Length)
print(stext)
