a=input()
b=eval(input())
v=eval(input())
l=v*v/(2*b)
print('The acceleration of %.d is %.2f M / s, the take-off speed is %.2f M / s, and the shortest take-off runway length is %.2f M.'%(a,b,v,l))
