cMale=int(input())
cFemale=int(input())
zMale=(cMale/(cMale+cFemale))
zFemale=(cFemale/(cMale+cFemale))
sText="The male students ratio is %.2f%,the female students ratio is %.2f%"(zMale,zFemale)
print(sText)
