planename=input()
a=float(input())
v=float(input())
length=float(v*v/(2*a))
print("The acceleration of",planename,"is","%.2f"%a,"M / s,the take-off speed is","%.2f"%v,"M / s and the shortest take-off runway length is","%.2f"%length,"M.")
