sName = input()
iAcce = eval(input())
ivelo = eval(input())
slength = (ivelo*ivelo)/(2*iAcce)
print("The acceleration of %s is %.2f M / s, the take-off speed is %.2f M / s, and the shortest take-off runway length is %.2f M."%(sName,iAcce,ivelo,slength))
