n = str(input())
v = float(input())
a = float(input())
l = v*v/(2*a)
print("The acceleration of n is %.2f M / s, the take-off speed is %.2f M / s, and the shortest take-off runway length is %.2f M."%(v,l))
