n=str(input())
a=eval(input())
v=int(input())
l=v*v/(2*a)
print("The acceleration of","%s"%n,"is""%.2f"%a,"M/s,""the take-off speed is","%.2f"%v,"M/s,""and the shortest take-off runway length is","%.2f"%l,"M." )      
