fName=str(input())
a=eval(input())
v=eval(input())
length=v*v/(a*2)
print("The acceleration of",fName,"is",a,"M / s, the take-off speed is",v,"M / s, and the shortest take-off runway length is %2f"%(length))
