fName=str(input())
a=float(input())
v=float(input())
length=v*v/(a*2)
print("The acceleration of",fName,"is %2fM / s,the take-off speed is %2fM / s,and the shortest take-off runway length is %2fM."%(a,v,length))
