sName = str(input())
a = float(input())
v = float(input())
length =(v*v)/(2*a)
print("The acceleration of",sName,"is%.2f" %a,"M / s,the take-off speed is%.2f" %v,"M / s,and the shortest take-off run way length is,%.2f" %length,"M.")
