import turtle
t = turtle.Pen()
t.penup()
t.fd(-250)
t.pendown()
t.pensize(25)
colorlist = ['red','orange','yellow','green','blue']
t.color("red")
t.seth(-40)
for i in range(4):
    t.circle(40, 80)
    t.circle(-40, 80)
t.color("orange")
t.circle(40, 80/2)
t.color("yellow")
t.fd(40)
t.color("green")
t.circle(16, 180)
t.color("blue")
t.fd(40*2/3)
turtle.done()
