n = input()
a = eval(input())
v = eval(input())
minilength = v*v/(2*a)
print("The acceleration of",n,"is %.2f M/s,the take-off speed is %.2f M / s,and the shortest take-off runway length is",minilength,"M."%(n,a))
