n = input()
a = eval(input())
v = eval(input())
minilength = v*v/(2*a)
print("The acceleration of",n,"is",a,"M/s,the take-off speed is",v,"M / s,and the shortest take-off runway length is",minilength,"M.")
