name = str(input())
a = float(input())
v = float(input())
l = v*v/(2*a)
print("The acceleration of %s is %.2fM/S, the take-off speed is %.2fM/S, and the shortest take-off runway length is %.2fM"%(name,a,v,l))
