name = str(input())
a = float(input())
v = float(input())
l = v*v/(2*a)
print("The acceleration of %s is %.2f M / S, the take-off speed is %.2f M / S, and the shortest take-off runway length is %.2f M"%(name,a,v,l))
