SName=input()
a=eval(input())
v=eval(input())
length=a*a/(2*v)
print("The acceleration of %s is %s M / s, the take-off speed is %s M / s, and the shortest take-off runway length is %.2f M."%(SName,a,v,length))
