name=(input())
a=eval(input())
v=eval(input())
length=eval(v*v/(2*a))
print("The acceleration of {} is {} M / s, the take-off speed is {} M / s, and the shortest take-off runway length is {} M."(name,a,v,length))
