name=input()
a=input()
v=input()
sa=float(a)
sv=float(a)
length=sv*sv/(sa*2)
print("The acceleration of ",name,"is",sa,"M / s,","the take-off speed is",sv,"M / s,","and the shortest take-off runway length is ",length,"M.")
