boynumber = eval(input())
girlnumber = eval(input())
maleratio =boynumber/(boynumber+girlnumber)
femaleratio = girlnumber/(boynumber+girlnumber)
print("The male students ratio is %.2f%%, the female students ratio is %.2f%%"%(maleratio,femaleratio ))
