n=input()
b=eval(input())
c=eval(input())
length=c*c/(2*b)
sText = "The acceleration of %s is %.2f M/s, the take off speed is %.2f M/s, and the shortest take-off runway length is %.2f M."%(n,b,c,length)
print(sText)
