n=input()
a=float(input())
v=int(input())
length=v*v/(2*a)
print("The acceleration of {} is {:.2f}  M / s, the take-off speed is {:.2f} M / s, and the shortest take-off runway length is {:.2f} M.".format(n,a,v,length))
