sN = input()
sA = eval(input())
sV = eval(input())
sL = sV*sV/(2*sA)
print('The acceleration of %s is %.2f M / s, the take-off speed is %.2f M / s, and the shortest take-off runway length is %.2f M.'%(sN,sA,sV,sL))
