a=input("name:")
b=float(input())
v=float(input())
l=(v**2)/(2*b)
c="The acceleration of %s is %.2fM / s, the take-off speed is %.2fM / s, and the shortest take-off runway length is %.2fM." %(a,b,v,l)
print(c)
