name=(input())
a=eval(input())
v=eval(input())
length=v*v/(a*2)
print("The acceleration of %s is %.2f M / s, the take-off speed is %.2f M / s, and the shortest take-off runway length is %.2f M."%(name,a,v,length))
