sName=input()
a=float(input())
v=float(input())
length=float(v*v/(2*a))
print("The acceleration of %s is %.2f M / s,the take-off speed is %.2f M / s,and the shortest take-off runway length is %.2f M." % (sName,a,v,length))
