pname = str(input())
pacc = eval(input())
pvel = eval(input())
plength = pvel*pvel/(pacc*2)
print("The acceleration of %s is %.2f M / s, the take-off speed is %.2f M / s, and the shortest take-off runway length is %.2f M."%(pname,pacc,pvel,plength))
