n=str(input(""))
a=eval(input(""))
v=eval(input(""))
length=v*v/(2*a)
print("The acceleration of %s"%(n),"is %.2f M / s,"%(a),"the take-off speed is %.2f M / s,"%(v),"and the shortest take-off runway length is %.2f M."%(length))
