sName=input()
A=eval(input())
V=eval(input())
L=V*V/(2*A)
print("The acceleration of %s is %.2f M / s, the take-off speed is %.2f M / s, and the shortest take-off runway length is %.2f M."%(sName,A,V,L))
