import turtle, random
t = turtle. Pen()
t.penup()
t.fd(-300)
t.pendown()
t.pensize(40)
colorlist = ("black","grey","blue","green","pink")
t.color("black")
t.seth(-40)
for i in range(5):
     t.color(random. choice(colorlist))
     t.circle(50, 60)
     t.circle(-50, 60)
t.color("grey")
t.circle(30, 40)
t.color("black")
t.fd(40)
t.circle(30,180)
t.color("pink")
t.fd(50)
t.circle(0,-90)
t.fd(70)
turtle.done()
