b=input()
a=eval(input())
v=eval(input())
length=v**2/(2*a)
print("The acceleration of %s is %.2f M / s, the take-off speed is %.2f M / s, the shortest take-off runway length isthe take-off speed is %.2f M"%(b,a,v,length))
