n=input()
a=eval(input())
v=eval(input())
length=v*v/(2*a)
print("The acceleration of",n,"is","%2.f"%a,"M / s,","the take-off speed is","%.2f"%v,"M / s, and the shortest take-off runway length is" , "%.2f"%length, "M.")
