n=input()
a=input(int())
v=input(int())
length=v*v/(2*a)
print("The acceleration of ", n, "is ", a%.2," M / s,"" the take-off speed is", v%.2, "M / s, and the shortest take-off runway length is" , length%.2, "M.")
