sname=input("")
a=input()
v=input()
length=v*v/(2*a)
print("The acceleration of B350 is ",sname," M / s", "the take-off speed is", a ,"M / s", "and the shortest take-off runway length is", length ,"M.")
