A=input()
a=input(float())
v=input(float())
B=float((v*v)/(2*a))
print("The acceleration of""%s%A""is""%2f%a""M/s,the take-off speed is""%2f%v""M/s,and the shortest take-off runway length is""%2f&B""M.")
