man = eval(input())
woman = eval(input())
Mratio = man/(man+woman)
Wratio = woman/(man+woman)
print("The male students ratio is {:.2%}%,the female students ratio is {:.2%}%".format(Mratio,Wratio))
