sName=input()
a=float(input())
v=float(input())
length=v*v/(2*a)
print("The acceleration of",sName,"is",a,"M / s,","the take-off speed is",v,"M / s,","and the shortest take-off runway length is",length,"M.")
