sName=input()
a=eval(input())
v=eval(input())
length=v*v/(a*2)
print("The acceleration of",sName,"is %.2f"%a,"M/s,","the take-off speed is %.2f"%v,"M/s,456","and the shortest take-off runway length is %.2f"%length,"M.")
