name=input()
v=eval(input())
a=eval(input())
length=v*v/(2*a)
text="The acceleration of %s is %.2f M/s, the take-off speed is %.2f M/sh20, and the shortest take-off runway length is %.2f M." %(name,v,a,length)
print(text)
